export const ProjectedTextures = {
    Water: 0,
    Pavement: 1,
    Asphalt: 2,
    Cobblestone: 3,
    FootballPitch: 4,
    BasketballPitch: 5,
    TennisCourt: 6,
    ManicuredGrass: 7,
    Cycleway: 8,
    Railway: 9,
    Rock: 10,
    Sand: 11,
    Hedge: 12,
    WoodFence: 13,
    ConcreteFence: 14,
    AsphaltRoad: 15,
    AsphaltUnmarkedRoad: 16,
    ConcreteRoad: 17,
    ConcreteUnmarkedRoad: 18,
    ConcreteIntersection: 19,
    WoodRoad: 20,
    Helipad: 21,
    Garden: 22,
    Soil: 23,
    Grass: 24,
    ForestFloor: 25,
    ChainLinkFence: 26,
    MetalFence: 27,
    StoneWall: 28,
    ConcreteWall: 29,
    Farmland0: 30,
    Farmland1: 31,
    Farmland2: 32,
    Gravel: 33,
    DirtRoad: 34,
    SandRoad: 35,
    RailwayTop: 36,
    Rail: 37,
    GenericPitch: 38
} as const satisfies Record<string, number>;

export const ExtrudedTextures = {
    // RoofGeneric1: 0,
    // RoofGeneric2: 1,
    RoofGeneric3: 0,
    // RoofGeneric4: 3,
    RoofTiles: 1,
    RoofMetal: 2,
    RoofConcrete: 3,
    RoofThatch: 4,
    RoofEternit: 5,
    RoofGrass: 6,
    RoofGlass: 7,
    RoofTar: 8,
    FacadeGlass: 9,
    FacadeBrickWall: 10,
    // FacadeBrickWindow: 11,
    FacadePlasterWall: 11,
    // FacadePlasterWindow: 12,
    FacadeWoodWall: 12,
    // FacadeWoodWindow: 15,
    FacadeBlockWall: 13,
    // FacadeBlockWindow: 17,
} as const satisfies Record<string, number>;